### ISSUE TITLE
[loopback-connector-mongodb] 6.2.0, raise error "Invalid URL" when mongoDB is for cluster

### ISSUE THREAD

**Issue by mstiunicon** [loopbackio/loopback-connector-mongodb#665] opened 2022-04-15 02:22 UTC
**package.json**
 
`    "loopback-connector-mongodb": "^6.2.0",`

Logs:
```
Cannot start the application. TypeError: Cannot initialize connector "mongodb": Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at MongoDB.connect (xxxxxxxxxxx\node_modules\loopback-connector-mongodb\lib\mongodb.js:337:20)
    at Object.initializeDataSource [as initialize] (xxxxxxxxxx\node_modules\loopback-connector-mongodb\lib\mongodb.js:127:28)        
    at FeederDataSource.DataSource.setup (xxxxxxxxxx\node_modules\loopback-datasource-juggler\lib\datasource.js:515:19)
```

**URL:**
`url =mongodb://admin:password@75a46762-47a8-477c-aaae-4c336442d784-0.databases.appdomain.cloud:32491,75a46762-47a8-477c-aaae-4c336442d784-1.databases.appdomain.cloud:32491,75a46762-47a8-477c-aaae-4c336442d784-2.databases.appdomain.cloud:32491/feeder?authSource=admin&replicaSet=replset&ssl=true&retryWrites=false&connectTimeoutMS=60000`

![image](https://user-images.githubusercontent.com/17581823/163507582-6a975f5e-54ab-4eef-83f5-f9acc3596d43.png)

I just create a simple test script to check the method "new URL(url)"
it raise same exception...

```
const url = "mongodb://admin:password@75a46762-47a8-477c-aaae-4c336442d784-0.databases.appdomain.cloud:32491,75a46762-47a8-477c-aaae-4c336442d784-1.databases.appdomain.cloud:32491,75a46762-47a8-477c-aaae-4c336442d784-2.databases.appdomain.cloud:32491/feeder?authSource=admin&replicaSet=replset&ssl=true&retryWrites=false&connectTimeoutMS=60000"
const urlObj = new URL(url)
console.log('urlObj=', urlObj)
```

**Comment by achrinza** [comment] 2022-04-15 07:13
Thanks for the report! It looks like this is a duplicate of https://github.com/loopbackio/loopback-connector-mongodb/issues/663. I'll proceed to close the issue in favour of https://github.com/loopbackio/loopback-connector-mongodb/issues/663.

If you believe this was done in error, please add a comment to re-open this issue.

**Comment by achrinza** [comment] 2022-04-15 07:13
Duplicate of https://github.com/loopbackio/loopback-connector-mongodb/issues/663

**Closed** 2022-04-15 07:13 UTC
